### ISSUE TITLE
After refresh the "My Questions" the question added one more time

### ISSUE THREAD

**Issue by Lener92** [MeQT/WSEDB#2]
Nachdem eine Frage hinzugefügt wurde (bei mir war es die erste und einzige Frage) und die Seite aktualisiert wurde, wurde die Frage jedes Mal neu hinzugefügt.
![bug](https://cloud.githubusercontent.com/assets/24453637/21544234/aef72a38-cdcd-11e6-8100-c980b9eb44a5.PNG)

**Comment by MeQT** [comment]
Hab das mal gefixed -> müssen wir dann die tage testen, konnte das aber danach nicht wieder reproduzieren.
