### ISSUE TITLE
Neue Frage hinzugefügt -> Button "Frage erstellen" verschiebt sich

### ISSUE THREAD

**Issue by Lener92** [MeQT/WSEDB#4]
Nachdem eine neue Frage hinzugefügt wurde, erscheint in der Frageübersicht eine Meldung "Frage erfolgreich gespeichert!", dabei verschiebt sich der Button "Neue Frage erstellen" nach rechts -> Button sollte da bleiben wo er hingehört.

**Comment by MeQT** [comment]
Done
